name: Build docker image, Push to Registry and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: alpha2j
          password: as5222165*

      - name: Generate Docker Tag Variable
        id: set-docker-tag-date
        run: echo "$(date+'%Y%m%d')" >> $DOCKER_TAG_DATE

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: alpha2j/private_repo:action_test1_${{ steps.set-docker-tag-date.outputs.DOCKER_TAG_DATE }}"
