name: Build docker image, Push to Registry and Deploy

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: alpha2j
          password: as5222165*

      - name: Set color
        id: random-color-generator
        run: echo "DOCKER_IMAGE_TAG_DATE=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_OUTPUT

      - name: Docker build, tag, push
        run: |
          docker build -t action_test:${{ steps.random-color-generator.outputs.DOCKER_IMAGE_TAG_DATE }} .
          docker tag action_test:${{ steps.random-color-generator.outputs.DOCKER_IMAGE_TAG_DATE }} alpha2j/private_repo:action_test_${{ steps.random-color-generator.outputs.DOCKER_IMAGE_TAG_DATE }}
          docker push alpha2j/private_repo:action_test_${{ steps.random-color-generator.outputs.DOCKER_IMAGE_TAG_DATE }}
